dist: trusty
sudo: required

language: python
python:
  - "3.6"

addons:
  apt:
    packages:
      - chromium-chromedriver
  chrome: stable

before_script:
  - "ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver"

env:
  - ATLAS_URL=https://www-test.ebi.ac.uk/gxa
  - ATLAS_URL=https://wwwdev.ebi.ac.uk/gxa

script: python -m unittest discover -v tests/